#DATABASE
spring:
  datasource:
    driver-class-name :
    url :
    username :
    password :

#JPA SQL
  jpa:
    show-sql:
    hibernate:
      ddl-auto:
    properties:
      dialect:
      hibernate:
        format_sql: