#DATABASE
spring:
  datasource:
    driver-class-name :
    url :
    username :
    password :

#JPA SQL
  jpa:
    show-sql : true
    format-sql : true
    #hibernate.ddl-auto : update
    dialect :